"""phase 8: ai analysis and ai insights

Revision ID: 05f3e5856776
Revises: b174b326aa27
Create Date: 2026-09-27 01:46:51.802469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05f3e5856776'
down_revision: Union[str, None] = 'b174b326aa27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('scope_key', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=10), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('context_version', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=10), nullable=False),
    sa.Column('day_score', sa.SmallInteger(), nullable=True),
    sa.Column('score_rationale', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('data_caveats', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('tomorrow_priorities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('token_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('token_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=8, scale=4), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_analysis_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analysis'))
    )
    op.create_index(op.f('ix_ai_analysis_context_hash'), 'ai_analysis', ['context_hash'], unique=False)
    op.create_index(op.f('ix_ai_analysis_user_id'), 'ai_analysis', ['user_id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('evidence_verified', sa.Boolean(), nullable=False),
    sa.Column('epistemic_status', sa.String(length=20), nullable=True),
    sa.Column('user_reaction', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis.id'], name=op.f('fk_ai_insights_analysis_id_ai_analysis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_insights'))
    )
    op.create_index(op.f('ix_ai_insights_analysis_id'), 'ai_insights', ['analysis_id'], unique=False)
    # raw_events_2026_09/10/11 are NOT part of the declared schema — see the Phase 4 migration's
    # matching comment. Deliberately not touched here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # raw_events_2026_09/10/11 are NOT part of the declared schema — see the Phase 4 migration's
    # matching comment. Deliberately not touched here.
    op.drop_index(op.f('ix_ai_insights_analysis_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_ai_analysis_user_id'), table_name='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_context_hash'), table_name='ai_analysis')
    op.drop_table('ai_analysis')
    # ### end Alembic commands ###
