"""phase 3: users, devices, enrollment codes, sync batches, raw events, seq gaps, dirty days

Revision ID: 2821164b9f4c
Revises: 
Create Date: 2026-09-14 01:18:59.684601

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2821164b9f4c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('day_start_hour', sa.SmallInteger(), server_default='4', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('browser_family', sa.String(length=20), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('token_rotated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('previous_token_hash', sa.String(length=255), nullable=True),
    sa.Column('previous_token_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_seq', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('capability_level', sa.String(length=30), nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('dirty_days',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('marked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dirty_days_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'local_date', name=op.f('pk_dirty_days'))
    )
    op.create_table('enrollment_codes',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('used_by_device_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollment_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_enrollment_codes'))
    )
    op.create_table('raw_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts_utc', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('tz_offset_min', sa.SmallInteger(), nullable=False),
    sa.Column('tz_id', sa.String(length=64), nullable=False),
    sa.Column('uptime_ms', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clock_suspect', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('schema_v', sa.SmallInteger(), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_raw_events_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_raw_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'ts_utc', name=op.f('pk_raw_events')),
    postgresql_partition_by='RANGE (ts_utc)'
    )
    op.create_table('seq_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('expected_seq', sa.BigInteger(), nullable=False),
    sa.Column('received_seq_from', sa.BigInteger(), nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_seq_gaps_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seq_gaps'))
    )
    op.create_index(op.f('ix_seq_gaps_device_id'), 'seq_gaps', ['device_id'], unique=False)
    op.create_table('sync_batches',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('seq_from', sa.BigInteger(), nullable=False),
    sa.Column('seq_to', sa.BigInteger(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sync_batches_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('pk_sync_batches'))
    )
    op.create_index(op.f('ix_sync_batches_device_id'), 'sync_batches', ['device_id'], unique=False)
    # ### end Alembic commands ###

    # raw_events is partitioned by month (§13, §29): a partitioned table with zero partitions
    # rejects every insert, so the current month plus the next two are created here at migration
    # time. Ongoing partitions beyond this are ensured at API startup by
    # timeos/jobs/partitions.py, which uses the same "create the next few months" strategy —
    # this migration only needs to cover the gap between "table exists" and "app has started
    # once". Computed from now() at migration RUN time, not from the date this file was
    # authored, so re-running this migration fresh at any point in the future still creates the
    # right partitions.
    op.execute("""
        DO $$
        DECLARE
            i INT;
            part_start DATE;
            part_end DATE;
            part_name TEXT;
        BEGIN
            FOR i IN 0..2 LOOP
                part_start := date_trunc('month', now() + (i || ' months')::interval)::date;
                part_end := (part_start + interval '1 month')::date;
                part_name := 'raw_events_' || to_char(part_start, 'YYYY_MM');
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF raw_events FOR VALUES FROM (%L) TO (%L)',
                    part_name, part_start, part_end
                );
            END LOOP;
        END $$;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_batches_device_id'), table_name='sync_batches')
    op.drop_table('sync_batches')
    op.drop_index(op.f('ix_seq_gaps_device_id'), table_name='seq_gaps')
    op.drop_table('seq_gaps')
    # DROP TABLE on a partitioned parent cascades to drop every child partition automatically —
    # no explicit partition cleanup needed here.
    op.drop_table('raw_events')
    op.drop_table('enrollment_codes')
    op.drop_table('dirty_days')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('users')
    # ### end Alembic commands ###
