"""phase 4: sessionization and analytics schema

Revision ID: 6f0231965ff2
Revises: 2821164b9f4c
Create Date: 2026-09-14 21:11:54.990078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f0231965ff2'
down_revision: Union[str, None] = '2821164b9f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('default_valence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['activity_categories.id'], name=op.f('fk_activity_categories_parent_id_activity_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_categories')),
    sa.UniqueConstraint('user_id', 'key', name='uq_activity_categories_user_id_key')
    )
    op.create_index(op.f('ix_activity_categories_user_id'), 'activity_categories', ['user_id'], unique=False)
    op.create_table('behavioral_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pattern_type', sa.String(length=40), nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('occurrences', sa.Integer(), server_default='1', nullable=False),
    sa.Column('strength', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('support', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='candidate', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_behavioral_patterns_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_behavioral_patterns'))
    )
    op.create_index(op.f('ix_behavioral_patterns_user_id'), 'behavioral_patterns', ['user_id'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('day_start_utc', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('day_end_utc', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observed_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tracked_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('idle_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unobserved_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('offline_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coverage_ratio', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('screen_time_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active_time_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deep_work_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('focused_work_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('shallow_work_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('communication_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('learning_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('entertainment_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('social_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('distraction_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('unknown_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('unknown_ratio', sa.Numeric(precision=4, scale=3), server_default='0', nullable=False),
    sa.Column('context_switches', sa.Integer(), server_default='0', nullable=False),
    sa.Column('switches_per_hour', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('interruptions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fragmentation_index', sa.Numeric(precision=4, scale=3), server_default='0', nullable=False),
    sa.Column('longest_focus_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('avg_focus_s', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('focus_session_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unlock_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tz_transition', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('revised', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_metrics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'local_date', name=op.f('pk_daily_metrics'))
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('intent', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('classification_source', sa.String(length=20), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('devices', postgresql.ARRAY(sa.String(length=120)), server_default='{}', nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], name=op.f('fk_activities_category_id_activity_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by'], ['activities.id'], name=op.f('fk_activities_superseded_by_activities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_category_id'), 'activities', ['category_id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('app_classifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('app_key', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('sample_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], name=op.f('fk_app_classifications_category_id_activity_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_app_classifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'app_key', name=op.f('pk_app_classifications'))
    )
    op.create_table('app_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('app_key', sa.String(length=255), nullable=False),
    sa.Column('app_label', sa.String(length=255), nullable=True),
    sa.Column('start_ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interaction_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('screen_state', sa.String(length=20), nullable=True),
    sa.Column('source_event_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_app_sessions_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_app_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_sessions'))
    )
    op.create_index(op.f('ix_app_sessions_device_id'), 'app_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_app_sessions_user_id'), 'app_sessions', ['user_id'], unique=False)
    op.create_table('device_coverage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('start_ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_coverage_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_coverage'))
    )
    op.create_index(op.f('ix_device_coverage_device_id'), 'device_coverage', ['device_id'], unique=False)
    # ### end Alembic commands ###
    # Not expressible as a SQLAlchemy column/table arg — hand-added (see device_coverage.py's
    # module docstring). Coverage intervals are a partition of time; this constraint makes the
    # database itself reject two overlapping intervals for the same device, rather than relying
    # on the pipeline to never produce that bug.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        "ALTER TABLE device_coverage ADD CONSTRAINT excl_device_coverage_no_overlap "
        "EXCLUDE USING gist (device_id WITH =, tstzrange(start_ts, end_ts) WITH &&)"
    )
    # raw_events_2026_09/10/11 are NOT part of the declared schema (they're dynamically-created
    # monthly partitions — see timeos/jobs/partitions.py and the Phase 3 migration's DO block) —
    # autogenerate proposes dropping them only because they aren't declared as SQLAlchemy models.
    # Deliberately not touched here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE device_coverage DROP CONSTRAINT excl_device_coverage_no_overlap")
    op.drop_index(op.f('ix_device_coverage_device_id'), table_name='device_coverage')
    op.drop_table('device_coverage')
    op.drop_index(op.f('ix_app_sessions_user_id'), table_name='app_sessions')
    op.drop_index(op.f('ix_app_sessions_device_id'), table_name='app_sessions')
    op.drop_table('app_sessions')
    op.drop_table('app_classifications')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_category_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_behavioral_patterns_user_id'), table_name='behavioral_patterns')
    op.drop_table('behavioral_patterns')
    op.drop_index(op.f('ix_activity_categories_user_id'), table_name='activity_categories')
    op.drop_table('activity_categories')
    # ### end Alembic commands ###
