"""phase 9: browser sessions

Revision ID: 6fec57d5fdee
Revises: 05f3e5856776
Create Date: 2026-09-27 16:20:26.891777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fec57d5fdee'
down_revision: Union[str, None] = '05f3e5856776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('browser_family', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('start_ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('truncated', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_browser_sessions_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_browser_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_browser_sessions'))
    )
    op.create_index(op.f('ix_browser_sessions_device_id'), 'browser_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_browser_sessions_user_id'), 'browser_sessions', ['user_id'], unique=False)
    # raw_events_2026_09/10/11 are NOT part of the declared schema — see the Phase 4 migration's
    # matching comment. Deliberately not touched here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # raw_events_2026_09/10/11 are NOT part of the declared schema — see the Phase 4 migration's
    # matching comment. Deliberately not touched here.
    op.drop_index(op.f('ix_browser_sessions_user_id'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_device_id'), table_name='browser_sessions')
    op.drop_table('browser_sessions')
    # ### end Alembic commands ###
