"""phase 5: focus sessions

Revision ID: 72c918b8c873
Revises: 17f668b8c1b7
Create Date: 2026-09-14 22:54:27.710850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72c918b8c873'
down_revision: Union[str, None] = '17f668b8c1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('start_ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interruption_count', sa.Integer(), nullable=False),
    sa.Column('tool_switch_count', sa.Integer(), nullable=False),
    sa.Column('attributed_ratio', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_deep_work', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], name=op.f('fk_focus_sessions_category_id_activity_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_focus_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_focus_sessions'))
    )
    op.create_index(op.f('ix_focus_sessions_user_id'), 'focus_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # raw_events_2026_09/10/11 are NOT part of the declared schema — see the Phase 4 migration's
    # matching comment. Deliberately not touched here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_focus_sessions_user_id'), table_name='focus_sessions')
    op.drop_table('focus_sessions')
    # ### end Alembic commands ###
