"""phase 6: goals, working hours, activity goal linkage

Revision ID: ad4b14e19681
Revises: 72c918b8c873
Create Date: 2026-09-20 15:10:02.716035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad4b14e19681'
down_revision: Union[str, None] = '72c918b8c873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('target_minutes_per_week', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('target_behavior', sa.String(length=500), nullable=True),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('working_hours',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_local', sa.Time(), nullable=False),
    sa.Column('end_local', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_working_hours_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'weekday', name=op.f('pk_working_hours'))
    )
    op.create_table('goal_activity_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('app_key', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint('(category_id IS NOT NULL) != (app_key IS NOT NULL)', name=op.f('ck_goal_activity_mapping_exactly_one_target')),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], name=op.f('fk_goal_activity_mapping_category_id_activity_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_goal_activity_mapping_goal_id_goals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_activity_mapping'))
    )
    op.create_index(op.f('ix_goal_activity_mapping_goal_id'), 'goal_activity_mapping', ['goal_id'], unique=False)
    op.add_column('activities', sa.Column('goal_id', sa.UUID(), nullable=True))
    op.add_column('activities', sa.Column('goal_confidence', sa.Numeric(precision=4, scale=3), nullable=True))
    op.create_foreign_key(op.f('fk_activities_goal_id_goals'), 'activities', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
    # raw_events_2026_09/10/11 are NOT part of the declared schema — see the Phase 4 migration's
    # matching comment. Deliberately not touched here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_activities_goal_id_goals'), 'activities', type_='foreignkey')
    op.drop_column('activities', 'goal_confidence')
    op.drop_column('activities', 'goal_id')
    op.drop_index(op.f('ix_goal_activity_mapping_goal_id'), table_name='goal_activity_mapping')
    op.drop_table('goal_activity_mapping')
    op.drop_table('working_hours')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
