"""phase 7: privacy audit events

Revision ID: b174b326aa27
Revises: ad4b14e19681
Create Date: 2026-09-27 00:12:42.741322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b174b326aa27'
down_revision: Union[str, None] = 'ad4b14e19681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacy_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('allowlist_version', sa.String(length=10), nullable=False),
    sa.Column('ai_share_app_names', sa.Boolean(), nullable=False),
    sa.Column('field_count', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('rejected_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_privacy_audit_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privacy_audit_events'))
    )
    op.create_index(op.f('ix_privacy_audit_events_user_id'), 'privacy_audit_events', ['user_id'], unique=False)
    # raw_events_2026_09/10/11 are NOT part of the declared schema — see the Phase 4 migration's
    # matching comment. Deliberately not touched here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # raw_events_2026_09/10/11 are NOT part of the declared schema — see the Phase 4 migration's
    # matching comment. Deliberately not touched here.
    op.drop_index(op.f('ix_privacy_audit_events_user_id'), table_name='privacy_audit_events')
    op.drop_table('privacy_audit_events')
    # ### end Alembic commands ###
